import type { Lead, Approval } from "./types";

export const MOCK_LEADS: Lead[] = [
  {
    id: "1",
    name: "Sarah Chen",
    email: "sarah@nexusai.io",
    company: "Nexus AI",
    intent: "Enterprise automation for sales ops team of 50. Ready to sign this quarter.",
    score: 0.92,
    route: "hot",
    status: "onboarding_complete",
    is_returning_customer: false,
    created_at: "2026-06-12T18:30:00Z",
  },
  {
    id: "2",
    name: "Marcus Webb",
    email: "marcus@growthlabs.com",
    company: "GrowthLabs",
    intent: "Exploring AI tools for lead qualification. Have budget but still evaluating.",
    score: 0.65,
    route: "warm",
    status: "content_warm_sent",
    is_returning_customer: true,
    created_at: "2026-06-12T17:45:00Z",
  },
  {
    id: "3",
    name: "Priya Sharma",
    email: "priya@buildfast.dev",
    company: "BuildFast",
    intent: "Just browsing, early stage startup, no immediate need.",
    score: 0.28,
    route: "cold",
    status: "content_cold_sent",
    is_returning_customer: false,
    created_at: "2026-06-12T16:20:00Z",
  },
  {
    id: "4",
    name: "Jordan Lee",
    email: "jordan@scaleup.co",
    company: "ScaleUp Co",
    intent: "Need CRM integration and automation ASAP, team of 30 reps.",
    score: 0.88,
    route: "hot",
    status: "onboarding_complete",
    is_returning_customer: true,
    created_at: "2026-06-12T15:00:00Z",
  },
  {
    id: "5",
    name: "Alex Rivera",
    email: "alex@dataflow.ai",
    company: "DataFlow AI",
    intent: "Evaluating multiple vendors, interested in automation features.",
    score: 0.54,
    route: "warm",
    status: "content_warm_sent",
    is_returning_customer: false,
    created_at: "2026-06-12T14:30:00Z",
  },
  {
    id: "6",
    name: "Nina Patel",
    email: "nina@velox.io",
    company: "Velox",
    intent: "Scaling outbound sales, need intelligent lead scoring ASAP.",
    score: 0.95,
    route: "hot",
    status: "onboarding_complete",
    is_returning_customer: false,
    created_at: "2026-06-12T13:10:00Z",
  },
  {
    id: "7",
    name: "Tom Nguyen",
    email: "tom@clearpath.com",
    company: "ClearPath",
    intent: "Looking at options for next quarter, not urgent.",
    score: 0.41,
    route: "warm",
    status: "content_warm_sent",
    is_returning_customer: false,
    created_at: "2026-06-12T11:05:00Z",
  },
];

export const MOCK_APPROVALS: Approval[] = [
  {
    id: "apr_001",
    action: "create_crm_contact",
    payload: { name: "Sarah Chen", email: "sarah@nexusai.io", company: "Nexus AI", score: 0.92 },
    agent: "onboarding",
    created_at: "2026-06-12T18:31:00Z",
  },
  {
    id: "apr_002",
    action: "create_crm_contact",
    payload: { name: "Jordan Lee", email: "jordan@scaleup.co", company: "ScaleUp Co", score: 0.88 },
    agent: "onboarding",
    created_at: "2026-06-12T15:01:00Z",
  },
];

export const MOCK_ACTIVITY = [
  { id: "a1", type: "hot", name: "Nina Patel", company: "Velox", action: "qualified as hot lead — booking call", time: "2m ago" },
  { id: "a2", type: "approval", name: "Sarah Chen", company: "Nexus AI", action: "CRM record pending your approval", time: "9m ago" },
  { id: "a3", type: "warm", name: "Tom Nguyen", company: "ClearPath", action: "added to nurture sequence", time: "32m ago" },
  { id: "a4", type: "hot", name: "Jordan Lee", company: "ScaleUp Co", action: "onboarding email delivered", time: "1h ago" },
  { id: "a5", type: "cold", name: "Priya Sharma", company: "BuildFast", action: "politely declined with resources", time: "2h ago" },
  { id: "a6", type: "warm", name: "Alex Rivera", company: "DataFlow AI", action: "nurture email sent", time: "3h ago" },
];
